### ISSUE TITLE
Show only branch with symbol?

### ISSUE THREAD

**Issue by capaldo** [sinetoami/lightline-hunks#3]
Is this possible?

**Comment by sinetoami** [comment]
Hey @capaldo, thanks for open this issue! I like this idea :+1:. Give me some time to work on it. I'm very busy now but I'll pay attention to this.

**Comment by sinetoami** [comment]
@capaldo 
Hope it's what you need. Thanks for this idea.

**Comment by capaldo** [comment]
It is thank you so much @sinetoami
